### PR TITLE
Pagination proposal - accounts

### PR DESCRIPTION
**Pull request by dgarcia360**
* Added new endpoint ``/accounts``.
* Pluralized accounts endpoints.

@Vektrat @martinayora If you agree with the proposal, please coordinate with the core devs if there is some missing index (e.g. importance, mosaicId balance).

_To discuss:_

The explorer requires to order accounts by network currency balance, but REST does not know about the main network currency. Instead, REST could filter by mosaic id implementing a broader solution. By doing so, client apps will be able to order accounts not only by the currency mosaic but also by any other mosaic.

The options to filter by in ``AccountOrderByEnum.yml`` are the following.

```
type: string
enum:
  - id
  - importance
  - balance[mosaicId]
```
The problem is that the SDKs won't be able to detect that the content between brackets in ``balance[mosaicId]`` could any value  (options are defined as an enum) because of the generated code.

@rg911 @fboucquez  Is it possible to parse the mosaicId from the enum at the SDK level? Would you prefer to define the multiple options as a regular string? Let me know if you can think of any other potential solution.

### CODE REVIEW

**Comment by fboucquez** [comment]
Why not just adding a mosaicId=xxx query param filter? We can also keep the enum string id | balance | importance

**Comment by rg911** [comment]
> Why not just adding a mosaicId=xxx query param filter? We can also keep the enum string = id | balance | importance, static strings representing a sortable attribute name.

That will work out as well but it means the endpoint only works for specific mosaicId? I think @dgarcia360 's original idea is to create an endpoint similar to the transaction search which can take all possible criteria. 

But first thing first is to confirm those indices are available. @Vektrat  @martinayora

**Comment by fboucquez** [comment]
If a user wants to sort by the balance of a mosaic, would the user care about balances or other mosaics? should accounts without that mosaic be returned?

There is a one-to-many account to mosaic association. 

MosaciId query filter is a bit odd as it filters out mosaics from accounts, not accounts directly (it's not an attribute of the account). If an account doesn't have any mosaic with the provided id, that account should be ignored I guess. 

Account 1 -> mosaicA (b 10), mosaicB (b 20), mosaicC (b 30)
Account 2 -> mosaicB (b 15), mosaicC (b 25)
Account 3 -> mosaicA (b 20), mosaicB (b 10)

If the users searches by mosaicId=A, orderBy=balance, order=desc, the response could be:

Account 3 -> mosaicA (b 20)
Account 1 -> mosaicA (b 10)

What do you think?

**Comment by dgarcia360** [comment]
Changed balance[mosaic] with filter `mosaicId=xxx  + orderBy=balance`

**Comment by AnthonyLaw** [comment]
> If an account doesn't have any mosaic with the provided id, that account should be ignored I guess.

Yes, agree!.

> The client would know who are richest. What do you think?

This is what we need for Explorer. (rich list and importance list)

Here is some something I wish to add on.

**Harvester list**
- total harvested blocks 
- total harvested fees

Example in NIS 
https://explorer.nemtool.com/#/harvesterlist

**Comment by dgarcia360** [comment]
> total harvested blocks
Will be supported by #93 

> total harvested fees

It's not planned to support this kind of query with the new search endpoint because it will require aggregating data for every account listed and would make the queries inefficient. 

However, it looks possible to have an endpoint to get the number of total harvested fees for a given account. @Anthony Could you please open a new issue describing how would you  like this endpoint to look like?

**Comment by evias** [comment]
@AnthonyLaw look at the PR for "blocks" endpoints. It has a parameter `signerPublicKey` and `beneficiaryPublicKey` which permits you to calculate "totals" by querying it.

**Comment by AnthonyLaw** [comment]
> @AnthonyLaw look at the PR for "blocks" endpoints. It has a parameter `signerPublicKey` and `beneficiaryPublicKey` which permits you to calculate "totals" by querying it.

thanks, it need recursive call to the rest endpoint, if the block height getting higher.
but using async in client side, should be fine.

**Comment by Vektrat** [comment]
i was just reviewing this PR and there are some expected concerns on the sorting capabilities:

**sorting by importance**
the database does not just have an `importance` field, so this becomes an overly specific endpoint, with a lot of complexity - i'm not saying we don't know how to do it, we even have the [fork's example](https://github.com/Alexhuszagh/catapult-rest/blob/02fea32d60b901001e2cdef2e18fd6b62c3e5725/rest/src/db/CatapultDb.js#L940), but such specific endpoint may not belong to the REST, and it's not just query complexity, but also performance issues due to how the data is stored to begin with:

```
        "importances" : [ 
            {
                "value" : NumberLong(2087500),
                "height" : NumberLong(4875)
            }, 
            {
                "value" : NumberLong(2087500),
                "height" : NumberLong(4836)
            }, 
            {
                "value" : NumberLong(2129166),
                "height" : NumberLong(4797)
            }
        ],
```

**sort by (mosaic)amount**
just like with importances, the data here is stored in an array fashion:
```
        "mosaics" : [ 
            {
                "id" : NumberLong(7070305841962119106),
                "amount" : NumberLong(299966669101199)
            }, 
            {
                "id" : NumberLong(4796875812706583418),
                "amount" : NumberLong(2000000)
            }
        ]
```
however this is not an issue here, because as you have already been discussing, we would always be limiting this query by a specific `mosaicId`, the resulting query is also not basic, but it does not go so far as in the importance case in regards of complexity - it is also a rather specific demand, but since it could be useful for other clients, and we would be offering a generic interface (to query by any given mosaicId/currency), the balance between complexity/specificity could be fine to implement this, though it'd most likely still require indexing (probably on amount, and i'm not sure if this would help much because this field has little clustering capabilities)

i'd like to get @Jaguar0625 involved in this conversation

also @evias do you know if you had performance issues or if you had to add custom indexes to the database for the fork's endpoint?

my initial suggestion would be to implement this without those sorting capabilities in order to progress, and keep on studying how to enhance the endpoint

**Comment by Vektrat** [comment]
@dgarcia360 what's the `address` param in the `/accounts` endpoint for?

**Comment by dgarcia360** [comment]
> @dgarcia360 what's the address param in the /accounts endpoint for?

Definitely not needed, it's a copy-paste mistake form the ``/transactions`` endpoint.

**Comment by Vektrat** [comment]
> i was just reviewing this PR and there are some expected concerns on the sorting capabilities:
> 
> **sorting by importance**
> the database does not just have an `importance` field, so this becomes an overly specific endpoint, with a lot of complexity - i'm not saying we don't know how to do it, we even have the [fork's example](https://github.com/Alexhuszagh/catapult-rest/blob/02fea32d60b901001e2cdef2e18fd6b62c3e5725/rest/src/db/CatapultDb.js#L940), but such specific endpoint may not belong to the REST, and it's not just query complexity, but also performance issues due to how the data is stored to begin with:
> 
> ```
>         "importances" : [ 
>             {
>                 "value" : NumberLong(2087500),
>                 "height" : NumberLong(4875)
>             }, 
>             {
>                 "value" : NumberLong(2087500),
>                 "height" : NumberLong(4836)
>             }, 
>             {
>                 "value" : NumberLong(2129166),
>                 "height" : NumberLong(4797)
>             }
>         ],
> ```
> 
> **sort by (mosaic)amount**
> just like with importances, the data here is stored in an array fashion:
> 
> ```
>         "mosaics" : [ 
>             {
>                 "id" : NumberLong(7070305841962119106),
>                 "amount" : NumberLong(299966669101199)
>             }, 
>             {
>                 "id" : NumberLong(4796875812706583418),
>                 "amount" : NumberLong(2000000)
>             }
>         ]
> ```
> 
> however this is not an issue here, because as you have already been discussing, we would always be limiting this query by a specific `mosaicId`, the resulting query is also not basic, but it does not go so far as in the importance case in regards of complexity - it is also a rather specific demand, but since it could be useful for other clients, and we would be offering a generic interface (to query by any given mosaicId/currency), the balance between complexity/specificity could be fine to implement this, though it'd most likely still require indexing (probably on amount, and i'm not sure if this would help much because this field has little clustering capabilities)
> 
> i'd like to get @Jaguar0625 involved in this conversation
> 
> also @evias do you know if you had performance issues or if you had to add custom indexes to the database for the fork's endpoint?
> 
> my initial suggestion would be to implement this without those sorting capabilities in order to progress, and keep on studying how to enhance the endpoint, though it is true that i see little point on this endpoint without sorting (this is why it wasn't available in the API to begin with ^^)

i've discussed with jaguar and here are the outcomes:
- there is indeed a not very friendly structure to offer the kind of queries requested
- it was suggested to specify a height when filtering by importance: discarding this idea because it does not feel very useful
- as everybody knows, sorting by mosaic amounts is a reasonable functionality, no one can guarantee decent performance with it

what we suggest from the REST side:
- discard importance sorting for now
- usually we would probably also discard the sorting by mosaic amounts, to offer instead accounts listing and see how things go, which is a basic feature that we didn't have until now, however, the reason it wasn't offered so far was because this endpoint seems to be pretty pointless and random without any kind of sorting - since it makes no sense, and we still would like to offer accounts in some way, we suggest to implement accounts listing sorting by mosaic-amount as requested, which is not a trivial query, but still not so heavy as the importance one (since we will be filtering by mosaicId), and see how it performs so far, and if it is bad, we will try to look for alternatives or reconsider

some things that arise and need to be decided here, are:
- do we still want to list/paginate (all) accounts? if so, how do we sort? id even if useless in 99% of the cases if not all?
- should we offer sorting just by `mosaic-amount`?
- if we offer only sorting by `mosaic-amount`, mosaicId must be provided, one approach would be to do it like so `/accounts/mosaic/:mosaicId`, the other would be to follow the usual with the new pagination and just provide `mosaicId` and `amount` filters, providing mosaicId alone could yield results, but sorting to be decided, and providing `amount` alone would result in error, the other option is that both filters are always needed
- the decision is a bit tricky because providing no filters returns mostly useless results (but still valid from an API point of view), and not providing the filters makes no sense, at the same time, both filters are kind of needed altogether

@dgarcia360

**Comment by dgarcia360** [comment]
The main goal of this proposal was to order the results and get rid of the fork. However, even if sorting is rejected,  networks could still use it to retrieve from REST statistics about the number of accounts, and a complete list of the accounts, so I would opt to keep it. If the network is small (does not have tons of accounts), the endpoint still relevant to not access MongoDB directly.

> should we offer sorting just by mosaic-amount?

If possible, by account importance and balance+mosaicId. Otherwise, if it's only possible by balance+mosaicId,  the default mosaicId could be the default network currency. 

* If REST does not know about the default network currency it's ok if the user has to provide the value. If orderBy=balance but mosaicId is not provided, REST could return the accounts ordered by entry id or raise an error.

**Comment by Vektrat** [comment]
> The main goal of this proposal was to order the results and get rid of the fork. However, even if sorting is rejected, networks could still use it to retrieve from REST statistics about the number of accounts, and a complete list of the accounts, so I would opt to keep it. If the network is small (does not have tons of accounts), the endpoint still relevant to not access MongoDB directly.
> 
> > should we offer sorting just by mosaic-amount?
> 
> If possible, by account importance and balance+mosaicId. Otherwise, if it's only possible by balance+mosaicId, the default mosaicId could be the default network currency. If REST does not know about the default network currency it's ok if the user has to provide the value. If orderBy=balance but mosaicId is not provided, REST could return the accounts ordered by entry id or raise an error.

- so from what you are saying we allow to sort by id
- also, as said, i'd prefer not to offer importance yet
- REST does not know about network currency so providing it is mandatory
- i'm against returning default-sorted results when mosaicId is not provided because it'd give the appearance that the endpoint is working as requested, when in reality, it is not (so raise error)

**Comment by dgarcia360** [comment]
@fboucquez Thanks Fernando for the commit! 

@Vektrat @fboucquez @rg911 @martinayora Could you please review it again? I think it looks ok to be merged.

**Pull request merged**
