### PR TITLE
Added new node public key

### PR DESCRIPTION
**Pull request by rg911**
Added new node public key to the node/info endpoint

### CODE REVIEW

**Review by fboucquez — CHANGES_REQUESTED** [review]
Is it possible to add a description explaining that it's used for node link and delegate harvesting?

**Comment by fboucquez** [comment]
About `publicKey`, `nodePublicKey` names. There are not good enough but we don't want to break too much. 

The renames would need to be done in another PR until we have all the upgrades in place at least from server and rest. 

https://github.com/nemtech/catapult-server/issues/110

What would it be good candidates from them? It seems like they have multiple uses.

Maaaybe:

- publicKey => caPublicKey  = coming from ca.pem.key file, the node main account public key, and certificate authority. 
- nodePublicKey = coming for node.pem.key file required for communication and delegate harvesting

**Comment by segfaultxavi** [comment]
Yes, definitely the `description` is missing :D

Regarding the names, I prefer names that are useful **to the user**, not based on where the property comes from.
For instance, I don't know if the user is familiar enough with the concept of Certificate Authority. Is this the key used for **signing** new blocks? Can we call it something like `signingPublicKey` or `harvestingPublicKey`?
Regarding `nodePublicKey`, this is also confusing, since all these keys are related to the node somehow. This is the key used to activate Delegated Harvesting, and it relates to TLS somehow, right? Can we call it something like `communicationPublicKey`, `tlsPublicKey`, `transamissionPublicKey`, `networkPublicKey`, ... ?

**Comment by fboucquez** [comment]
Atm you cannot put `description` or `summary` next to a `ref` element. This will change in the  next open api spec

https://github.com/OAI/OpenAPI-Specification/issues/1514

Let's revisit this when 1) we rename the key fields according to what we agree on server/bootstrap/rest/etc
2) when we upgrade the open api spec eventually

**Review by fboucquez — APPROVED** [review]

**Comment by segfaultxavi** [comment]
> Atm you cannot put `description` or `summary` next to a `ref` element. This will change in the next open api spec

Related: #233

**Pull request merged**
