### PR TITLE
Pagination proposal - receipts

### PR DESCRIPTION
**Pull request by dgarcia360**
Please, pay extra attention to this proposal because instead of reducing the number of endpoints, it creates three new endpoints to be able to paginate between the different collections:

* ``GET /statements/transaction?height=<HEIGHT>&...``
* ``GET /statements/resolutions/mosaic?height=<HEIGHT>&...``
* ``GET /statements/resolutions/address?height=<HEIGHT>&...``

Review the filters suggested for every collection, and do not hesitate to propose more of them if needed. 

Note that for "/transaction/statements" we are proposing filters such as ``receiptType``, ``artifactId``, ``recipientAddress`` or ``senderAddress``. In this case, if one statement has one receipt matching the filter, it should be returned the whole statement and not just the receipt.

### CODE REVIEW

**Comment by Vektrat** [comment]
should `/blocks/{height}/statements/{hash}/merkle` be part of this?

- as far as i know, `hash` is a transaction hash, not a statement hash (don't even think there's such a thing?) so `/statements/{hash}` looks weird to me
- endpoint starts with `/blocks...`,
- endpoint does not return any statements, rather a merkle tree which is a representation of the state of the block

**Comment by dgarcia360** [comment]
> as far as i know, hash is a transaction hash, not a statement hash (don't even think there's such a thing?) so /statements/{hash} looks weird to me.

Each statement has a hash, maybe you are confusing ``getMerkleTransaction`` with the endpoint with ``getMerkleReceipts``?

> endpoint starts with /blocks...,

This is to match getMerkleTransaction ``/blocks/{height}/transactions/{hash}/merkle``. What we could do is to move the endpoint under blocks instead of receipts.

> endpoint does not return any statements, rather a merkle tree which is a representation of the state of the block.

Not sure to follow, ``merkle`` is stated alreadt at the end of the endpoint. Could you please share an alternative?

**Comment by Vektrat** [comment]
> Each statement has a hash, maybe you are confusing `getMerkleTransaction` with the endpoint with `getMerkleReceipts`?
yeah i was mixing them up

> This is to match getMerkleTransaction `/blocks/{height}/transactions/{hash}/merkle`. What we could do is to move the endpoint under blocks instead of receipts.

> Not sure to follow, `merkle` is stated alreadt at the end of the endpoint. Could you please share an alternative?

it's true that merkle is at the end, but what i mean is that this endpoint is returning info on the block level after all (even though it is related to statements), so i was just pointing out to consider that in terms of documentation maybe this could be moved to the blocks endpoints (though it may just be better here, because it is related to statements), either way i don't think any of the options is wrong, was just saynig to think on it rather than just automatically put it to receipts because it is related to receipts

**Comment by dgarcia360** [comment]
@rg911 @Vektrat @fboucquez any other modification do you want to add? I think looks ok to be merged, please review when you have some time.

**Comment by rg911** [comment]
> @rg911 @Vektrat @fboucquez any other modification do you want to add? I think looks ok to be merged, please review when you have some time.

I would restore the previous getByheight if possible. Main it would be good to have the endpoint return `statement`

**Comment by dgarcia360** [comment]
> I would restore the previous getByheight if possible. 

Not sure to follow - the previous endpoint did not have pagination. The new endpoint allows you to filter by height, but also by other parameters. This is especially useful if you want to track, for example, all the balances deducted from your account not represented as transactions without having to stick it to a block.

> Main it would be good to have the endpoint return statement.

The current endpoints return arrays of statements (transaction statements, mosaic resolution statements, and namespaces resolution statements). Note that's not possible to paginate over three different collections in the same endpoint.

**Comment by rg911** [comment]
> > I would restore the previous getByheight if possible.
> 
> Not sure to follow - the previous endpoint did not have pagination. The new endpoint allows you to filter by height, but also by other parameters. This is especially useful if you want to track, for example, all the balances deducted from your account not represented as transactions without having to stick it to a block.
> 
> > Main it would be good to have the endpoint return statement.
> 
> The current endpoints return arrays of statements (transaction statements, mosaic resolution statements, and namespaces resolution statements). Note that's not possible to paginate over three different collections in the same endpoint.

Should we have both? the resolveAlias which used the Statement at a specific height. To get all resolution receipts you have to call the search twice and you can only use the height in filter. adding other filters will compromise the resolution results.

**Pull request merged**
