### PR TITLE
Added a new endpoint to list finalized blocks

### PR DESCRIPTION
**Pull request by Vektrat**
Related to #183

### CODE REVIEW

**Comment by Vektrat** [comment]
thinking of adding `latestFinalizedHeight` to `/chain/info`

@AnthonyLaw how useful would be this endpoint from a client perspective? i mean `/finalizedBlocks`, sounds pretty useless to me but 🤷‍♂️

**Comment by fboucquez** [comment]
If collections allow it, instead of creating a new finalization block search, I would add a `finalizationPoint` field to the existing block endpoints. If the block has `finalizationPoint`, it's finalized. If possible, I would also add a finalizationPoint search criteria if the user wants to search finalized /blocks by finalizationPoint ( == < or > kind of searches)

**Review by rg911 — CHANGES_REQUESTED** [review]
Should finalized block just be a block with finalization state? In addition, to return an array of blocks, it would be better to have an endpoint returning a single finalized block providing either Height or Hash. Or even perhaps we don't need the search endpoint at all?

**Comment by Vektrat** [comment]
you can read more info here: https://github.com/nemtech/catapult-rest/issues/457

**Comment by Vektrat** [comment]
as discussed in https://github.com/nemtech/catapult-rest/issues/457 we are dropping progress on this endpoint because we've come up with an alternative that makes this redundant, we will leave this issue for a while to see if the need arises in some point when clients integrate, and otherwise end up closing this

**Pull request closed without merging**
