### PR TITLE
drop phantom message.type

### LINKED ISSUE #219: drop phantom message.type in transfer message
ref https://github.com/nemtech/catapult-server/commit/aefe54fe9893163e46fe196fa1f31120bc376857

### PR DESCRIPTION
**Pull request by rg911**
Fixed #219

### CODE REVIEW

**Review by Vektrat — APPROVED** [review]

**Comment by Vektrat** [comment]
do we need a `MessageDTO` now?

**Comment by rg911** [comment]
Do we need the `payload` at all? or just use `message` as a string? @Vektrat

**Comment by Vektrat** [comment]
> Do we need the `payload` at all? or just use `message` as a string? @Vektrat

well this is what i asked xD

**Comment by rg911** [comment]
> > Do we need the `payload` at all? or just use `message` as a string? @Vektrat
> 
> well this is what i asked xD

okay, removed

**Review by Vektrat — APPROVED** [review]

**Review by fboucquez — APPROVED** [review]

**Pull request merged**
