### PR TITLE
Added state hash docs

### LINKED ISSUE #56: Document State merkle paths
https://github.com/nemtech/catapult-rest/pull/225

### PR DESCRIPTION
**Pull request by dgarcia360**
Closes #56

### CODE REVIEW

**Comment by dgarcia360** [comment]
Tagging this issue as blocked until we solve a couple of things:

* Could not test that the endpoint is working correctly since there is no way to serialize conveniently a state hash on the client-side. Related issue: https://github.com/nemtech/catbuffer/pull/15

* The response of the endpoint differs from other Merkle state endpoints.

**State merkle path response** -> ```{"tree":  ['ABC..', 'BCD...']} ```

**Receipt/transaction merkle path reponse** --> ```{"merklePath": [{"position": 1,"hash": "ABC..."}]}```

**Comment by Vektrat** [comment]
this looks right but as i told David i could not test it (can't serialize state), for the same reason i'm unsure if this tree is enough to validate the data

the tree is different from previous merkle trees because REST is spitting catapult-rest objects directly, and as far as i know it is slightly different (patricia tries), unsure if the verification process is the same as with merkles

**Comment by Vektrat** [comment]
after contacting core again, this is confirmed to be done, ready, and useful, so it's ready for development client side

jag:

> imo it is still useful. you can cryptographically prove an account has a certain balance at the tail of the chain. (edited) 
> there is always sporadic conversation of having "archive" nodes that will allow state lookups and proofs at arbitrary (or at least predefined) heights, but to my knowledge no work has happened to this effect

**Comment by Vektrat** [comment]
confirmed this is staying as `current` as for now

https://nemgroup-workspace.slack.com/archives/C015AEQ9ZL2/p1601364329132200?thread_ts=1601295012.098700&cid=C015AEQ9ZL2

**Comment by Vektrat** [comment]
@segfaultxavi not sure why this was undone / still a draft

it's a feature that has been available for months in REST, and should be added, it is probably detached from the repository and might need a new branch for it to be more easily put rather than rebasing and fixing the conflicts within this one

**Comment by segfaultxavi** [comment]
What's the status of this, @fboucquez? Should I try to fix conflicts and merge this PR, or is more work coming in the 3 issues you linked above?

**Comment by fboucquez** [comment]
I've been working on rest, it doesn't seem correct. I need to figure out the payload from server.

**Comment by segfaultxavi** [comment]
OK. I'll wait on your input then.

**Comment by fboucquez** [comment]
This PR is invalid, the /merkle endpoints replace it.

**Pull request closed without merging**
