### PR TITLE
Proposal getNetworkProperties

### PR DESCRIPTION
**Pull request by dgarcia360**
Suggestion for https://github.com/nemtech/catapult-rest/issues/64

**Note for SDK devs:** Do not implement until REST devs confirm that adding this endpoint is feasible.

### CODE REVIEW

**Comment by fboucquez** [comment]
Should we add the currency name?

https://nem2.slack.com/archives/GMUA2SD7E/p1579793932004300

**Comment by dgarcia360** [comment]
@Vektrat The current implementation formats mosaic ids differently to other endpoints:

Example:

*** /network/properties**

currencyMosaicId: "0x621E'C5B4'0385'6FC2" 

*** /account/:accountId**

id : "621EC5B403856FC2"

I believe that SDKs devs would appreciate if the currencyMosaicId could be parsed to the standard format.

**Comment by dgarcia360** [comment]
@fboucquez I'd not add aliases info to this endpoint. Note that ``/network/properties`` is just dumping the contents from a file without doing any extra verification.  You could add manually to your node any additional info you want to display, e.g. alias, although **it's not recommended to edit the file**. 

Secondly, another reason not to add it by default is that using the mosaic id is enough to issue all kind of transactions, and does not generate extra receipts. If needed, the alias can still be retrieved by asking it to REST with a second call.

Finally, note that the network / harvest mosaic does not require to be aliased to make the network operative. Some networks could even decide to disable the alias plugin from their networks completely.

**Comment by Vektrat** [comment]
> @Vektrat The current implementation formats mosaic ids differently to other endpoints:
> 
> Example:
> 
>     * **/network/properties**
> 
> 
> currencyMosaicId: "0x621E'C5B4'0385'6FC2"
> 
>     * **/account/:accountId**
> 
> 
> id : "621EC5B403856FC2"
> 
> I believe that SDKs devs would appreciate if the currencyMosaicId could be parsed to the standard format.

sadly we are outputting a config file here, which was probably filled by a human, it's one of the caveats of having to fetch a file and show it as is, instead of accessing some kind of endpoint that provides this information to the REST server

i'd leave it as it is now to avoid having a layer of specific parsing, the same happens with values such as `10'000` and `3650d` which in my opinion are worse than the mosaicId one

anyway will this endpoint be used by SDKs? i expected this to be used by more specific applications that would access the REST directly (like the fees)

**Pull request merged**
